version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@13.13.7

executors:
  my-custom-executor:
    docker:
      - image: python:slim-bookworm
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/platforminfo/platforminfo/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    resource_class: medium
  executor-for-pytesting:
    docker:
      - image: fedorapython/fedora-python-tox:f37
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/platforminfo/platforminfo/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    resource_class: large
jobs:
  python-build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          pip3 install yapf setuptools build
          python3 -m build
          mv dist/ /tmp/dist
          cp /tmp/dist/*.whl /tmp/platforminfo-build.whl
      - persist_to_workspace:
          root: /
          paths:
            - tmp/dist
      - store_artifacts:
          path: /tmp/platforminfo-build.whl
          destination: platforminfo-nightly.whl
  pypi:
    executor: my-custom-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: Upload package
          command: ls -la /tmp/dist && echo "listed" && bash build-scripts-cci/pypi-upload.sh

  example-job:
    executor: executor-for-pytesting
    steps:
      - checkout
      - run:
          pip3 install coverage pytest 
      - coverage-reporter/send_report:
          project-token: b2bb25a02462405ea5fca0bbebc25131 
          skip: false 

workflows:
  build-nightly:
    jobs:
      - python-build:
          filters:
            branches:
              only:
                - development
                - main
      - pypi:
          requires:
              - python-build
          filters:
            branches:
              only:
                - main
