version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@13.13.7

executors:
  my-custom-executor:
    docker:
      - image: fedorapython/fedora-python-tox:latest
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/platforminfo/platforminfo/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    resource_class: medium
jobs:
  python-build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          pip3 install yapf setuptools build
          python3 -m build
          mv dist/ /tmp/dist
          cp /tmp/dist/*.whl /tmp/platforminfo-build.whl
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: |
                sudo pip install pipenv
                pipenv install twine
                pipenv run twine upload /tmp/dist/*
      - store_artifacts:
          path: /tmp/platforminfo-build.whl
          destination: platforminfo-nightly.whl
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - coverage-reporter/send_report:
          project-token: b2bb25a02462405ea5fca0bbebc25131 
          skip: false 

workflows:
  build-nightly:
    jobs:
      - python-build:
          filters:
            branches:
              only:
                - development
                - main
  example-workflow:
    jobs:
      - example-job:
          filters:
            branches:
              only:
                - development
